

# Modbus READ Function Codes
MODBUS_FC_READ_COILS = 1
MODBUS_FC_READ_DISCRETE_INPUTS = 2
MODBUS_FC_READ_HOLDING_REGISTERS = 3
MODBUS_FC_READ_INPUT_REGISTERS = 4

# Modbus WRITE Function Codes
MODBUS_FC_WRITE_SINGLE_COIL = 5
MODBUS_FC_WRITE_SINGLE_REGISTER = 6

MODBUS_FC_READ_EXCEPTION_STATUS = 7
MODBUS_FC_DIAGNOSTICS = 8
MODBUS_FC_GET_COMM_EVENT_COUNTER = 11
MODBUS_FC_GET_COMM_EVENT_LOG = 12
MODBUS_FC_WRITE_MULTIPLE_COILS = 15
MODBUS_FC_WRITE_MULTIPLE_REGISTERS = 16
MODBUS_FC_REPORT_SERVER_ID = 17
MODBUS_FC_READ_FILE_RECORD = 20
MODBUS_FC_WRITE_FILE_RECORD = 21
MODBUS_FC_MASK_WRITE_REGISTER = 22
MODBUS_FC_RW_MULTIPLE_REGISTERS = 23
MODBUS_FC_READ_FIFO_QUEUE = 24
MODBUS_FC_ENCAPSULATED_INTERFACE_TRANSPORT = 43